/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PilotRegistrationIndexImport } from './routes/pilot-registration/index'
import { Route as OrgRegistrationIndexImport } from './routes/org-registration/index'
import { Route as RegAuthorityOrganizationsImport } from './routes/reg-authority/organizations'
import { Route as PilotRegistrationSuccessImport } from './routes/pilot-registration/success'
import { Route as OrgRegistrationSuccessImport } from './routes/org-registration/success'
import { Route as LoginPilotImport } from './routes/login/pilot'
import { Route as LoginOrganizationImport } from './routes/login/organization'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PilotRegistrationIndexRoute = PilotRegistrationIndexImport.update({
  id: '/pilot-registration/',
  path: '/pilot-registration/',
  getParentRoute: () => rootRoute,
} as any)

const OrgRegistrationIndexRoute = OrgRegistrationIndexImport.update({
  id: '/org-registration/',
  path: '/org-registration/',
  getParentRoute: () => rootRoute,
} as any)

const RegAuthorityOrganizationsRoute = RegAuthorityOrganizationsImport.update({
  id: '/reg-authority/organizations',
  path: '/reg-authority/organizations',
  getParentRoute: () => rootRoute,
} as any)

const PilotRegistrationSuccessRoute = PilotRegistrationSuccessImport.update({
  id: '/pilot-registration/success',
  path: '/pilot-registration/success',
  getParentRoute: () => rootRoute,
} as any)

const OrgRegistrationSuccessRoute = OrgRegistrationSuccessImport.update({
  id: '/org-registration/success',
  path: '/org-registration/success',
  getParentRoute: () => rootRoute,
} as any)

const LoginPilotRoute = LoginPilotImport.update({
  id: '/login/pilot',
  path: '/login/pilot',
  getParentRoute: () => rootRoute,
} as any)

const LoginOrganizationRoute = LoginOrganizationImport.update({
  id: '/login/organization',
  path: '/login/organization',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login/organization': {
      id: '/login/organization'
      path: '/login/organization'
      fullPath: '/login/organization'
      preLoaderRoute: typeof LoginOrganizationImport
      parentRoute: typeof rootRoute
    }
    '/login/pilot': {
      id: '/login/pilot'
      path: '/login/pilot'
      fullPath: '/login/pilot'
      preLoaderRoute: typeof LoginPilotImport
      parentRoute: typeof rootRoute
    }
    '/org-registration/success': {
      id: '/org-registration/success'
      path: '/org-registration/success'
      fullPath: '/org-registration/success'
      preLoaderRoute: typeof OrgRegistrationSuccessImport
      parentRoute: typeof rootRoute
    }
    '/pilot-registration/success': {
      id: '/pilot-registration/success'
      path: '/pilot-registration/success'
      fullPath: '/pilot-registration/success'
      preLoaderRoute: typeof PilotRegistrationSuccessImport
      parentRoute: typeof rootRoute
    }
    '/reg-authority/organizations': {
      id: '/reg-authority/organizations'
      path: '/reg-authority/organizations'
      fullPath: '/reg-authority/organizations'
      preLoaderRoute: typeof RegAuthorityOrganizationsImport
      parentRoute: typeof rootRoute
    }
    '/org-registration/': {
      id: '/org-registration/'
      path: '/org-registration'
      fullPath: '/org-registration'
      preLoaderRoute: typeof OrgRegistrationIndexImport
      parentRoute: typeof rootRoute
    }
    '/pilot-registration/': {
      id: '/pilot-registration/'
      path: '/pilot-registration'
      fullPath: '/pilot-registration'
      preLoaderRoute: typeof PilotRegistrationIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/organization': typeof LoginOrganizationRoute
  '/login/pilot': typeof LoginPilotRoute
  '/org-registration/success': typeof OrgRegistrationSuccessRoute
  '/pilot-registration/success': typeof PilotRegistrationSuccessRoute
  '/reg-authority/organizations': typeof RegAuthorityOrganizationsRoute
  '/org-registration': typeof OrgRegistrationIndexRoute
  '/pilot-registration': typeof PilotRegistrationIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login/organization': typeof LoginOrganizationRoute
  '/login/pilot': typeof LoginPilotRoute
  '/org-registration/success': typeof OrgRegistrationSuccessRoute
  '/pilot-registration/success': typeof PilotRegistrationSuccessRoute
  '/reg-authority/organizations': typeof RegAuthorityOrganizationsRoute
  '/org-registration': typeof OrgRegistrationIndexRoute
  '/pilot-registration': typeof PilotRegistrationIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login/organization': typeof LoginOrganizationRoute
  '/login/pilot': typeof LoginPilotRoute
  '/org-registration/success': typeof OrgRegistrationSuccessRoute
  '/pilot-registration/success': typeof PilotRegistrationSuccessRoute
  '/reg-authority/organizations': typeof RegAuthorityOrganizationsRoute
  '/org-registration/': typeof OrgRegistrationIndexRoute
  '/pilot-registration/': typeof PilotRegistrationIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/organization'
    | '/login/pilot'
    | '/org-registration/success'
    | '/pilot-registration/success'
    | '/reg-authority/organizations'
    | '/org-registration'
    | '/pilot-registration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login/organization'
    | '/login/pilot'
    | '/org-registration/success'
    | '/pilot-registration/success'
    | '/reg-authority/organizations'
    | '/org-registration'
    | '/pilot-registration'
  id:
    | '__root__'
    | '/'
    | '/login/organization'
    | '/login/pilot'
    | '/org-registration/success'
    | '/pilot-registration/success'
    | '/reg-authority/organizations'
    | '/org-registration/'
    | '/pilot-registration/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginOrganizationRoute: typeof LoginOrganizationRoute
  LoginPilotRoute: typeof LoginPilotRoute
  OrgRegistrationSuccessRoute: typeof OrgRegistrationSuccessRoute
  PilotRegistrationSuccessRoute: typeof PilotRegistrationSuccessRoute
  RegAuthorityOrganizationsRoute: typeof RegAuthorityOrganizationsRoute
  OrgRegistrationIndexRoute: typeof OrgRegistrationIndexRoute
  PilotRegistrationIndexRoute: typeof PilotRegistrationIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginOrganizationRoute: LoginOrganizationRoute,
  LoginPilotRoute: LoginPilotRoute,
  OrgRegistrationSuccessRoute: OrgRegistrationSuccessRoute,
  PilotRegistrationSuccessRoute: PilotRegistrationSuccessRoute,
  RegAuthorityOrganizationsRoute: RegAuthorityOrganizationsRoute,
  OrgRegistrationIndexRoute: OrgRegistrationIndexRoute,
  PilotRegistrationIndexRoute: PilotRegistrationIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login/organization",
        "/login/pilot",
        "/org-registration/success",
        "/pilot-registration/success",
        "/reg-authority/organizations",
        "/org-registration/",
        "/pilot-registration/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login/organization": {
      "filePath": "login/organization.tsx"
    },
    "/login/pilot": {
      "filePath": "login/pilot.tsx"
    },
    "/org-registration/success": {
      "filePath": "org-registration/success.tsx"
    },
    "/pilot-registration/success": {
      "filePath": "pilot-registration/success.tsx"
    },
    "/reg-authority/organizations": {
      "filePath": "reg-authority/organizations.tsx"
    },
    "/org-registration/": {
      "filePath": "org-registration/index.tsx"
    },
    "/pilot-registration/": {
      "filePath": "pilot-registration/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
